# Copied mostly from
# https://hackernoon.com/deploying-confidently-haskell-and-circle-ci-53cc44a300b4
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: sudo apt-get update
      - run: sudo apt-get install libcurl4-openssl-dev

      - restore-cache:
          keys:
            - stack-all-{{checksum "stack.yaml"}}-{{checksum "zbot.cabal"}}

      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
      - run: sudo mkdir /tmp/stack-download
      - run: sudo tar -xzf /tmp/stack.tar.gz -C /tmp/stack-download
      - run: sudo chmod +x /tmp/stack-download/stack-1.7.1-linux-x86_64/stack
      - run: sudo mv /tmp/stack-download/stack-1.7.1-linux-x86_64/stack /usr/bin/stack

      - run: stack setup
      - run: stack test

      - save-cache:
          key:  stack-all-{{checksum "stack.yaml"}}-{{checksum "zbot.cabal"}}
          paths:
            - ".stack-work"
            - "~/.stack"
